- name: Delete IPTables Playbook
  hosts: firewall
  become: yes
  gather_facts: no
  tasks:
    - name: iptables delete playbook
      shell: iptables -t filter -D DOCKER-USER -s "{{ target_ip_field }}" -j DROP
