- name: Second Apply IPTables Playbook
  hosts: firewall
  become: yes
  gather_facts: no
  tasks:
    - name: iptables second apply playbook
      shell: iptables -t filter -I DOCKER-USER -s "{{ source_ip }}" -j DROP -m comment --comment "Temporary block"

    - name: iptables second cancel playbook
      shell: echo "iptables -t filter -D DOCKER-USER -s {{ source_ip }} -j DROP -m comment --comment \"Temporary block\"" | at now + "{{ block_duration_minutes }}" minutes
