- name: Check Swarm Service Playbook
  hosts: swarm
  become: yes
  gather_facts: no
  tasks:
    - name: get replicas by service name
      shell: docker service ls --format "{{ '{{.Name}}' }} {{ '{{.Replicas}}' }}" | grep "\b.*{{ service_name }}\b" | awk '{ print $2 }'
      register: service_check
      ignore_errors: true

    - name: fail if container does not exist
      fail:
        msg: "The '{{ service_name }}' service does not exist!"
      when: service_check.stdout == ""

    - name: compare replicas
      fail:
        msg: "The replicas {{ service_name }} do not match the expected replicas {{ replicas_result }}"
      when: replicas_result != service_check.stdout
      vars:
        replicas_result: "{{ current_docker_replicas }}"
