- name: Check Mod Security Playbook
  hosts: firewall
  become: yes
  gather_facts: no
  tasks:
    - name: get container name
      shell: docker ps -a --filter "name=^/{{ modsec_container_name }}$" --format "{{ '{{.Status}}' }}"
      register: container_check
      ignore_errors: true

    - name: fail if container does not exist
      fail:
        msg: "The container '{{ modsec_container_name }}' does not exist!"
      when: container_check.stdout == ""

    - name: fail if container status does not not Up
      fail:
        msg: "Container '{{ modsec_container_name }}' exists but is not running."
      when: "'Up' not in container_check.stdout"
