- name: Only IP Regex Apply Mod Security Playbook
  hosts: firewall
  become: yes
  gather_facts: no
  tasks:
    - name: modsec create ip regex playbook for ip
      shell: echo "SecRule REMOTE_ADDR \"@ipMatch {{ secrule_ip }}\" \"id:{{ secrule_id_ip }},setvar:'tx.inbound_anomaly_score_threshold={{ secrule_anomaly_score }}',setvar:'tx.blocking_paranoia_level={{ secrule_paranoia_level }}',setvar:'tx.detection_paranoia_level=%{TX.blocking_paranoia_level}',phase:1\"" > {{ secrule_file }}.conf

    - name: modsec create ip regex playbook for chain
      shell: echo "SecRule FULL_REQUEST \"@rx {{ secrule_regex }}\" \"id:{{ secrule_id_chain }},phase:2,deny,log,chain\"" >> {{ secrule_file }}.conf

    - name: modsec chain ip regex playbook for chain
      shell: echo "    SecRule REMOTE_ADDR \"@ipMatch {{ secrule_ip }}\" \"t:none,log\"" >> {{ secrule_file }}.conf

    - name: validate
      shell: sed -i "s/'\"/'\\\\\"/g; s/@backspace@/\\\b/g" {{ secrule_file }}.conf

    # - name: modsec apply change playbook
    #   shell: docker container exec -it "{{ modsec_container_name }}" /bin/bash -c "nginx -s reload"

    - block:
        - name: modsec apply change playbook
          shell: docker container exec -it "{{ modsec_container_name }}" /bin/bash -c "nginx -s reload"
          register: task_result
          ignore_errors: yes
        
        - name: check if task failed
          fail:
            msg: "Task failed with error: {{ task_result.stdout }}"
          when: task_result.failed

      rescue:
        - name: delete secrule file if error
          shell: rm -rf {{ secrule_file }}.conf
        
        - name: apply change again
          shell: docker container exec -it "{{ modsec_container_name }}" /bin/bash -c "nginx -s reload"
        
        - name:
          fail:
            msg: "{{ ansible_failed_result.msg }}"

