- name: Only Regex And Payload Apply Mod Security Playbook
  hosts: firewall
  become: yes
  gather_facts: no
  tasks:
    - name: modsec create regex payload playbook for deny
      shell: echo "SecRule FULL_REQUEST \"@rx {{ secrule_regex }}\" \"id:{{ secrule_id }},phase:2,deny,log\"" >> {{ secrule_file }}.conf

    - name: validate
      shell: sed -i "s/'\"/'\\\\\"/g; s/@backspace@/\\\b/g" {{ secrule_file }}.conf

    # - name: modsec apply change playbook
    #   shell: docker container exec -it "{{ modsec_container_name }}" /bin/bash -c "nginx -s reload"

    - block:
        - name: modsec apply change playbook
          shell: docker container exec -it "{{ modsec_container_name }}" /bin/bash -c "nginx -s reload"
          register: task_result
          ignore_errors: yes
        
        - name: check if task failed
          fail:
            msg: "Task failed with error: {{ task_result.stdout }}"
          when: task_result.failed

      rescue:
        - name: delete secrule file if error
          shell: rm -rf {{ secrule_file }}.conf
        
        - name: apply change again
          shell: docker container exec -it "{{ modsec_container_name }}" /bin/bash -c "nginx -s reload"
        
        - name:
          fail:
            msg: "{{ ansible_failed_result.msg }}"

